### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'java Test': 'java Test'

### ISSUE THREAD

**Issue by hjq133** [crclz/jwdbg#1]
### 运行环境:
python 3.7.6

### 命令
python jwdbg.py -cmd "java Test" -case case1.yml

### 报错:
line70 : FileNotFoundError: [Errno 2] No such file or directory: 'java Test': 'java Test'

### 修复:
在第70行处，subprocess.Popen()函数里设置了shell=True.
(我运行的时候不设置shell=True会找不到java命令．．．)

**Comment by crclz** [comment]
感谢。
代码已修改。
